# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
FROM docker.elastic.co/elasticsearch/elasticsearch:6.0.0
COPY --chown=elasticsearch:elasticsearch config/elasticsearch.yml /usr/share/elasticsearch/config/
