version: '3.1'

services:
  collegefinder:
    image: hansb/collegefinder
    environment:
      - NODE_ENV=production
      - COLLEGESCORECARD_API_KEY_SECRET_FILE=/run/secrets/collegescorecard_api_key
    secrets:
      - collegescorecard_api_key
    ports:
      - 3000:3000
    
secrets:
  collegescorecard_api_key:
    external: true