version: '3.1'

services:
  data-service:
    environment:
      - NODE_ENV=development
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/index.js
  front-end:
    environment: 
      - NODE_ENV=development
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/index.js
