version: '3.1'

services:
  data-service:
    build: ./data-service
    image: collegefinder/data-service
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    ports:
      - 3000:3000
    volumes:
      - logs:/var/log/collegefinder/
  front-end:
    build: ./front-end
    image: collegefinder/front-end
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATASERVICE_HOST=data-service
      - DATASERVICE_PORT=3000
    ports:
      - 80:3001
    depends_on: 
      - data-service
      - redis
    volumes:
      - logs:/var/log/collegefinder/
  redis:
    build: ./redis
    volumes:
      - redis_data:/data
  elasticsearch:
    build: ./logging/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  logstash:
    build: ./logging/logstash
    volumes:
      - logs:/var/log/collegefinder/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LOG_LEVEL: warn
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build: ./logging/kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment: 
      LOGGING_QUIET: "true"

volumes:  
  redis_data:
  logs:
  elastic_data:

networks: 
  elk:
    driver: bridge