version: '3.1'

services:
  data-service:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=trace
    ports:
      - 9229:9229
    command: npm run debugmode
  front-end:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=trace
    ports:
      - 9230:9229
    command: npm run debugmode