version: '3.1'

services:
  data-service:
    build: ./data-service
    image: collegefinder/data-service
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
  front-end:
    build: ./front-end
    image: collegefinder/front-end
    environment:
      - NODE_ENV=production
    ports:
      - 80:3000
    depends_on: 
      - data-service