version: '3.1'

services:
  data-service:
    build: ./data-service
    image: collegefinder/data-service
    environment:
      - NODE_ENV=production
      - COLLEGESCORECARD_API_KEY_SECRET_FILE=/run/secrets/collegescorecard_api_key
    secrets:
      - collegescorecard_api_key
    ports:
      - 3000:3000
  front-end:
    build: ./front-end
    image: collegefinder/front-end
    environment:
      - NODE_ENV=production
    ports:
      - 80:3000
    
secrets:
  collegescorecard_api_key:
    external: true